public enum SFSAction
{
    PING = 1,
    MESSAGE_ERROR = 2,
    JOIN_ZONE_SUCCESS = 3,
    LOAD_USER_INFO = 4,
    LOAD_LIST_HERO_INFO = 5,
    TEAM_COMMIT = 6,
    COMBAT_BOT = 7,
    LOAD_TEAM = 8,
    BUY_STAMINA = 9,
    COMBAT_PREPARE = 10,
    COMBAT_DATA = 11,
    PVE_SURRENDER = 12,
    PVE_CONFIRM = 13,
    PVE_PLAY = 14,
    BUY_SLOT = 20,
    CHEAT_SAILOR = 101,
}
