name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: <?xml version="1.0" encoding="UTF-8"?><root>\n    <License id="Terms">\n        <MachineBindings>\n            <Binding Key="1" Value="576562626572264761624c65526f7578"/>\n            <Binding Key="2" Value="576562626572264761624c65526f7578"/>\n        </MachineBindings>\n        <MachineID Value="D7nTUnjNAmtsUMcnoyrqkgIbYdM="/>\n        <SerialHash Value="c30501dad3a686efd38c8d1ea3ba7f4d96a5954a"/>\n        <Features>\n            <Feature Value="33"/>\n            <Feature Value="1"/>\n            <Feature Value="12"/>\n            <Feature Value="2"/>\n            <Feature Value="24"/>\n            <Feature Value="3"/>\n            <Feature Value="36"/>\n            <Feature Value="17"/>\n            <Feature Value="19"/>\n            <Feature Value="62"/>\n            <Feature Value="60"/>\n        </Features>\n        <DeveloperData Value="AQAAAEY0LUhTN1gtVDVHQS1YU0VELTk5M1EtVTQ5Tg=="/>\n        <SerialMasked Value="F4-HS7X-T5GA-XSED-993Q-XXXX"/>\n        <StartDate Value="2021-10-06T00:00:00"/>\n        <StopDate Value="2022-04-22T15:53:22"/>\n        <UpdateDate Value="2022-03-24T14:53:22"/>\n        <InitialActivationDate Value="2021-10-06T07:53:04"/>\n        <LicenseVersion Value="6.x"/>\n        <ClientProvidedVersion Value="2021.2.7f1"/>\n        <AlwaysOnline Value="false"/>\n        <Entitlements>\n            <Entitlement Ns="unity_editor" Tag="UnityPersonal" Type="EDITOR" ValidTo="9999-12-31T00:00:00"/>\n            <Entitlement Ns="unity_editor" Tag="DarkSkin" Type="EDITOR_FEATURE" ValidTo="9999-12-31T00:00:00"/>\n        </Entitlements>\n    </License>\n<Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#Terms"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>ZmKZOj+6/uCDKsZgkhHdinalriE=</DigestValue></Reference></SignedInfo><SignatureValue>fHTGM/fv3s0EeeNvZffAgDO503nTQ9oshQDrrPYTt6tWPOw8alSb13H7MYBtC7XQa1JYjUh/9VOQ&#13;\nQgYqV2RuX/cHj5+biN0+f60cqdG80rv7YbMihXyRAGesya+VTYCMmW+RA6I13WxATgdOcqf/q2zi&#13;\nWO+uDnPuxjlpxUCBAztkNT+QtG6NN+gGYro66+WCD5iYrTqFqAc3ME5QcalF2ZYdWAM+zVG+Uwsf&#13;\nBsPFJBLVclzB9oRHZ3BxN+WOwk8Jh84WZVQbY3ULqCHlyJz5SnFkuhLWQvsZYqUznP7NW7+DWaiI&#13;\n+Fx7ATSMfcCUzenvTXZAJ7Ny2OmSo3kVHCK2Nw==</SignatureValue></Signature></root>
        with:
          githubToken: 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

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: = <?xml version="1.0" encoding="UTF-8"?><root>\n    <License id="Terms">\n        <MachineBindings>\n            <Binding Key="1" Value="576562626572264761624c65526f7578"/>\n            <Binding Key="2" Value="576562626572264761624c65526f7578"/>\n        </MachineBindings>\n        <MachineID Value="D7nTUnjNAmtsUMcnoyrqkgIbYdM="/>\n        <SerialHash Value="c30501dad3a686efd38c8d1ea3ba7f4d96a5954a"/>\n        <Features>\n            <Feature Value="33"/>\n            <Feature Value="1"/>\n            <Feature Value="12"/>\n            <Feature Value="2"/>\n            <Feature Value="24"/>\n            <Feature Value="3"/>\n            <Feature Value="36"/>\n            <Feature Value="17"/>\n            <Feature Value="19"/>\n            <Feature Value="62"/>\n            <Feature Value="60"/>\n        </Features>\n        <DeveloperData Value="AQAAAEY0LUhTN1gtVDVHQS1YU0VELTk5M1EtVTQ5Tg=="/>\n        <SerialMasked Value="F4-HS7X-T5GA-XSED-993Q-XXXX"/>\n        <StartDate Value="2021-10-06T00:00:00"/>\n        <StopDate Value="2022-04-22T15:53:22"/>\n        <UpdateDate Value="2022-03-24T14:53:22"/>\n        <InitialActivationDate Value="2021-10-06T07:53:04"/>\n        <LicenseVersion Value="6.x"/>\n        <ClientProvidedVersion Value="2021.2.7f1"/>\n        <AlwaysOnline Value="false"/>\n        <Entitlements>\n            <Entitlement Ns="unity_editor" Tag="UnityPersonal" Type="EDITOR" ValidTo="9999-12-31T00:00:00"/>\n            <Entitlement Ns="unity_editor" Tag="DarkSkin" Type="EDITOR_FEATURE" ValidTo="9999-12-31T00:00:00"/>\n        </Entitlements>\n    </License>\n<Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#Terms"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>ZmKZOj+6/uCDKsZgkhHdinalriE=</DigestValue></Reference></SignedInfo><SignatureValue>fHTGM/fv3s0EeeNvZffAgDO503nTQ9oshQDrrPYTt6tWPOw8alSb13H7MYBtC7XQa1JYjUh/9VOQ&#13;\nQgYqV2RuX/cHj5+biN0+f60cqdG80rv7YbMihXyRAGesya+VTYCMmW+RA6I13WxATgdOcqf/q2zi&#13;\nWO+uDnPuxjlpxUCBAztkNT+QtG6NN+gGYro66+WCD5iYrTqFqAc3ME5QcalF2ZYdWAM+zVG+Uwsf&#13;\nBsPFJBLVclzB9oRHZ3BxN+WOwk8Jh84WZVQbY3ULqCHlyJz5SnFkuhLWQvsZYqUznP7NW7+DWaiI&#13;\n+Fx7ATSMfcCUzenvTXZAJ7Ny2OmSo3kVHCK2Nw==</SignatureValue></Signature></root>
          UNITY_EMAIL: tienthanhit97@gmail.com
          UNITY_PASSWORD: Thanhtien01
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
